### ISSUE TITLE
Corrección de preavaluos

### ISSUE THREAD

**Issue by ferminarellano** [ferminarellano/inmodatav2#48]
El pre-avaluo debe jalar únicamente el avalúo más reciente de los inmuebles seleccionados.

**Comment by JDiGregorio** [comment]
El pre-avalúo jala únicamente los avaluos más recientes de los inmuebles seleccionados, se realizaron pruebas, **no se encontró bug en la consulta**. 

**El problema que se encontró:** 
El usuario ingreso dos veces el mismo inmueble y se crearon avaluos del inmueble original como del duplicado por ello al momento de crear el pre-avalúo jala la información de ambos.

**Comment by ferminarellano** [comment]
Gracias @JDiGregorio , verifiqué y en efecto el problema es debido a la duplicación de inmuebles. Esperemos se solucione con el #49
